echo "xing1" >> xing.txt
echo "xing2" >> xing.txt
echo "xing3" >> xing.txt
echo "xing4" >> xing.txt
echo "xing5" >> xing.txt
echo "xing6" >> xing.txt
echo "xing7" >> xing.txt
echo "xing8" >> xing.txt
echo "xing9" >> xing.txt
